- name: Install Kafka and Zookeeper
  hosts: 127.0.0.1
  pre_tasks:
  - name: Update apt
    become: yes
    apt:
      cache_valid_time: 1800
      update_cache: yes
    tags:
      - build
  roles:
    - name: sansible.zookeeper
      sansible_zookeeper_download_url: https://archive.apache.org/dist/zookeeper/zookeeper-3.4.13/zookeeper-3.4.13.tar.gz
    - name: sansible.kafka

- name: Install PostgreSQL
  hosts: 127.0.0.1
  roles:
  - name: geerlingguy.postgresql
